### ISSUE TITLE
create kanso package for defaultable module

### ISSUE THREAD

**Issue by caolan** [nodejitsu/defaultable#1]
Check it works in the browser and create a kanso.json file so it can be uploaded to package repositories and used as a dependency in kanso projects

**Comment by jhs** [comment]
I think the only issue you may have is the `require()` wrapper I recently implemented. Otherwise it's pretty pure Javascript.

There is a test suite but I have no idea how easily node-tap is to move to the browser. My hunch is it's not worth it.

**Comment by caolan** [comment]
Yeah, I'm just going to manually poke around using the examples from the README. We can look at getting tests running another time.

The require wrapper is the cause of most browser incompatibilities. The module object is a little different in node, couchdb and kanso.

Kanso is missing module.require property, which I can add easily enough. Couchdb and kanso are both missing module.filename, but that looks like its not used by defaultable if module.require is available anyway. There's a dependency on node's path module, but thankfully I've already ported this for kanso, so that should work without modification.

Other than that there's Array.isArray which isn't in couchdb's spidermonkey, but easy to implement.

**Comment by caolan** [comment]
Got it working client-side in chrome, but a few issues outstanding when calling it on couchdb itself. A few instances of Object.keys to fix too.

**Comment by caolan** [comment]
The best solution seems to be using module.id when module.filename is unavailable (in couchdb and the browser). Without being able to run the test suite in the browser its a bit difficult to understand if this will introduce and strange side-effects, but it seems to work for some basic examples.

**Comment by caolan** [comment]
https://github.com/iriscouch/defaultable/commit/7ccb345177d33062311769507d35d0946398d6b9
